import React from "react";
import './TextStroke.css'

const Suporters = () => {
  return (
    <div>
    <div className="   py-20  mx-auto flex px-4 2xl:max-w-[1440px]  xl:max-w-[1200px] lg:max-w-[1000px] md:max-w-[800px] sm: max-w-[500px] ">
      <div className="flex space-x-16 overflow-hidden ">
        <div className=" flex  space-x-16 loop-image ">
          <img
            decoding="async"
            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/one.png"
            alt="Image"
            className="max-w-none"
          ></img>
          <img
            decoding="async"
            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/four.png"
            alt="Image"
            className="max-w-none"
          ></img>
          <img
            decoding="async"
            className="max-w-none"
            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/five.png"
            alt="Image"
          ></img>

          <img
            decoding="async"
            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/three-1.png"
            alt="Image"
            className="max-w-none"
          ></img>
          <img
            decoding="async"
            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/two-1.png"
            alt="Image"
            className="max-w-none"
          ></img>

          <img
            decoding="async"
            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/one.png"
            alt="Image"
            className="max-w-none"
          ></img>
          <img
            decoding="async"
            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/four.png"
            alt="Image"
            className="max-w-none"
          ></img>
          <img
            decoding="async"
            className="max-w-none"
            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/five.png"
            alt="Image"
          ></img>

          <img
            decoding="async"
            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/three-1.png"
            alt="Image"
            className="max-w-none"
          ></img>
          <img
            decoding="async"
            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/two-1.png"
            alt="Image"
            className="max-w-none"
          ></img>
          <img
            decoding="async"
            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/one.png"
            alt="Image"
            className="max-w-none"
          ></img>
          <img
            decoding="async"
            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/four.png"
            alt="Image"
            className="max-w-none"
          ></img>
          <img
            decoding="async"
            className="max-w-none"
            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/five.png"
            alt="Image"
          ></img>

          <img
            decoding="async"
            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/three-1.png"
            alt="Image"
            className="max-w-none"
          ></img>
          <img
            decoding="async"
            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/two-1.png"
            alt="Image"
            className="max-w-none"
          ></img>

          <img
            decoding="async"
            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/one.png"
            alt="Image"
            className="max-w-none"
          ></img>
          <img
            decoding="async"
            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/four.png"
            alt="Image"
            className="max-w-none"
          ></img>
          <img
            decoding="async"
            className="max-w-none"
            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/five.png"
            alt="Image"
          ></img>

          <img
            decoding="async"
            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/three-1.png"
            alt="Image"
            className="max-w-none"
          ></img>
          <img
            decoding="async"
            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/two-1.png"
            alt="Image"
            className="max-w-none"
          ></img>
        </div>
        <div
          className=" flex  space-x-16 loop-image "
          aria-hidden="true"
        >
          <img
            decoding="async"
            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/one.png"
            alt="Image"
            className="max-w-none"
          ></img>
          <img
            decoding="async"
            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/four.png"
            alt="Image"
            className="max-w-none"
          ></img>
          <img
            decoding="async"
            className="max-w-none"
            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/five.png"
            alt="Image"
          ></img>

          <img
            decoding="async"
            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/three-1.png"
            alt="Image"
            className="max-w-none"
          ></img>
          <img
            decoding="async"
            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/two-1.png"
            alt="Image"
            className="max-w-none"
          ></img>

          <img
            decoding="async"
            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/one.png"
            alt="Image"
            className="max-w-none"
          ></img>
          <img
            decoding="async"
            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/four.png"
            alt="Image"
            className="max-w-none"
          ></img>
          <img
            decoding="async"
            className="max-w-none"
            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/five.png"
            alt="Image"
          ></img>

          <img
            decoding="async"
            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/three-1.png"
            alt="Image"
            className="max-w-none"
          ></img>
          <img
            decoding="async"
            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/two-1.png"
            alt="Image"
            className="max-w-none"
          ></img>
          <img
            decoding="async"
            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/one.png"
            alt="Image"
            className="max-w-none"
          ></img>
          <img
            decoding="async"
            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/four.png"
            alt="Image"
            className="max-w-none"
          ></img>
          <img
            decoding="async"
            className="max-w-none"
            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/five.png"
            alt="Image"
          ></img>

          <img
            decoding="async"
            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/three-1.png"
            alt="Image"
            className="max-w-none"
          ></img>
          <img
            decoding="async"
            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/two-1.png"
            alt="Image"
            className="max-w-none"
          ></img>

          <img
            decoding="async"
            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/one.png"
            alt="Image"
            className="max-w-none"
          ></img>
          <img
            decoding="async"
            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/four.png"
            alt="Image"
            className="max-w-none"
          ></img>
          <img
            decoding="async"
            className="max-w-none"
            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/five.png"
            alt="Image"
          ></img>

          <img
            decoding="async"
            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/three-1.png"
            alt="Image"
            className="max-w-none"
          ></img>
          <img
            decoding="async"
            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/two-1.png"
            alt="Image"
            className="max-w-none"
          ></img>
        </div>
      </div>
    </div>
    
    </div>
    
  );
};
export default Suporters;
