import { useTranslation } from 'react-i18next';
import './TextStroke.css';

const Suporters = () => {
    const { i18n } = useTranslation();
    const isRTL = i18n.dir() === 'rtl';
    return (
        <div>
            <div className="sm: mx-auto flex max-w-[500px] px-4 py-20 md:max-w-[800px] lg:max-w-[1000px] xl:max-w-[1200px] 2xl:max-w-[1440px]">
                <div className="flex space-x-16 overflow-hidden">
                    <div className="loop-image flex space-x-16">
                        <img
                            decoding="async"
                            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/one.png"
                            alt="Image"
                            className="max-w-none"
                        ></img>
                        <img
                            decoding="async"
                            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/four.png"
                            alt="Image"
                            className="max-w-none"
                        ></img>
                        <img
                            decoding="async"
                            className="max-w-none"
                            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/five.png"
                            alt="Image"
                        ></img>

                        <img
                            decoding="async"
                            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/three-1.png"
                            alt="Image"
                            className="max-w-none"
                        ></img>
                        <img
                            decoding="async"
                            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/two-1.png"
                            alt="Image"
                            className="max-w-none"
                        ></img>

                        <img
                            decoding="async"
                            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/one.png"
                            alt="Image"
                            className="max-w-none"
                        ></img>
                        <img
                            decoding="async"
                            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/four.png"
                            alt="Image"
                            className="max-w-none"
                        ></img>
                        <img
                            decoding="async"
                            className="max-w-none"
                            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/five.png"
                            alt="Image"
                        ></img>

                        <img
                            decoding="async"
                            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/three-1.png"
                            alt="Image"
                            className="max-w-none"
                        ></img>
                        <img
                            decoding="async"
                            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/two-1.png"
                            alt="Image"
                            className="max-w-none"
                        ></img>
                        <img
                            decoding="async"
                            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/one.png"
                            alt="Image"
                            className="max-w-none"
                        ></img>
                        <img
                            decoding="async"
                            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/four.png"
                            alt="Image"
                            className="max-w-none"
                        ></img>
                        <img
                            decoding="async"
                            className="max-w-none"
                            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/five.png"
                            alt="Image"
                        ></img>

                        <img
                            decoding="async"
                            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/three-1.png"
                            alt="Image"
                            className="max-w-none"
                        ></img>
                        <img
                            decoding="async"
                            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/two-1.png"
                            alt="Image"
                            className="max-w-none"
                        ></img>

                        <img
                            decoding="async"
                            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/one.png"
                            alt="Image"
                            className="max-w-none"
                        ></img>
                        <img
                            decoding="async"
                            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/four.png"
                            alt="Image"
                            className="max-w-none"
                        ></img>
                        <img
                            decoding="async"
                            className="max-w-none"
                            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/five.png"
                            alt="Image"
                        ></img>

                        <img
                            decoding="async"
                            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/three-1.png"
                            alt="Image"
                            className="max-w-none"
                        ></img>
                        <img
                            decoding="async"
                            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/two-1.png"
                            alt="Image"
                            className="max-w-none"
                        ></img>
                    </div>
                    <div className="loop-image flex space-x-16" aria-hidden="true">
                        <img
                            decoding="async"
                            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/one.png"
                            alt="Image"
                            className="max-w-none"
                        ></img>
                        <img
                            decoding="async"
                            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/four.png"
                            alt="Image"
                            className="max-w-none"
                        ></img>
                        <img
                            decoding="async"
                            className="max-w-none"
                            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/five.png"
                            alt="Image"
                        ></img>

                        <img
                            decoding="async"
                            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/three-1.png"
                            alt="Image"
                            className="max-w-none"
                        ></img>
                        <img
                            decoding="async"
                            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/two-1.png"
                            alt="Image"
                            className="max-w-none"
                        ></img>

                        <img
                            decoding="async"
                            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/one.png"
                            alt="Image"
                            className="max-w-none"
                        ></img>
                        <img
                            decoding="async"
                            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/four.png"
                            alt="Image"
                            className="max-w-none"
                        ></img>
                        <img
                            decoding="async"
                            className="max-w-none"
                            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/five.png"
                            alt="Image"
                        ></img>

                        <img
                            decoding="async"
                            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/three-1.png"
                            alt="Image"
                            className="max-w-none"
                        ></img>
                        <img
                            decoding="async"
                            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/two-1.png"
                            alt="Image"
                            className="max-w-none"
                        ></img>
                        <img
                            decoding="async"
                            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/one.png"
                            alt="Image"
                            className="max-w-none"
                        ></img>
                        <img
                            decoding="async"
                            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/four.png"
                            alt="Image"
                            className="max-w-none"
                        ></img>
                        <img
                            decoding="async"
                            className="max-w-none"
                            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/five.png"
                            alt="Image"
                        ></img>

                        <img
                            decoding="async"
                            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/three-1.png"
                            alt="Image"
                            className="max-w-none"
                        ></img>
                        <img
                            decoding="async"
                            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/two-1.png"
                            alt="Image"
                            className="max-w-none"
                        ></img>

                        <img
                            decoding="async"
                            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/one.png"
                            alt="Image"
                            className="max-w-none"
                        ></img>
                        <img
                            decoding="async"
                            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/four.png"
                            alt="Image"
                            className="max-w-none"
                        ></img>
                        <img
                            decoding="async"
                            className="max-w-none"
                            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/five.png"
                            alt="Image"
                        ></img>

                        <img
                            decoding="async"
                            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/three-1.png"
                            alt="Image"
                            className="max-w-none"
                        ></img>
                        <img
                            decoding="async"
                            src="https://gossip-themes.com/xpovio/wp-content/uploads/2024/01/two-1.png"
                            alt="Image"
                            className="max-w-none"
                        ></img>
                    </div>
                </div>
            </div>
        </div>
    );
};
export default Suporters;
